### ISSUE TITLE
这种垃圾为什么会有人star？

### ISSUE THREAD

**Issue by langxing** [ChenTianSaber/ScreenRecorderShoter#2]

**Comment by ChenTianSaber** [comment]
你气急败坏的样子看得我很开心

**Comment by langxing** [comment]
> 你气急败坏的样子看得我很开心

看你小人得志的嘴脸，我觉得恶心

**Comment by ChenTianSaber** [comment]
这Issue我不关，妈的莫名其妙跑来我这里骂一句，傻逼吗

**Comment by langxing** [comment]
> 这Issue我不关，妈的莫名其妙跑来我这里骂一句，傻逼吗

我还怕你关了？传两个文件夹就来糊弄人，谁傻逼谁清楚

**Comment by ChenTianSaber** [comment]
这他妈配老子的博客一起看的
我他妈爱传啥传啥，就是有人给我点，你有本事骂他们啊？
自己项目没人点star，都嫉妒的心理变态心脏萎缩傻气上头了
他妈自己不反思反思你那个破玩意儿为啥没人点吗？
傻逼，妈的三年前的项目莫名其妙跑来骂一句
脑子有泡

**Comment by langxing** [comment]
> 这他妈配老子的博客一起看的
> 我他妈爱传啥传啥，就是有人给我点，你有本事骂他们啊？
> 自己项目没人点star，都嫉妒的心理变态心脏萎缩傻气上头了
> 他妈自己不反思反思你那个破玩意儿为啥没人点吗？
> 傻逼，妈的三年前的项目莫名其妙跑来骂一句
> 脑子有泡

别迫害妄想症了好嘛，我只是因为这个项目下载下来完全跑不了，所以愤怒。你上传这么个不能跑的东西，有必要？

**Comment by ChenTianSaber** [comment]
你跑不了你水平问题呗
早说跑不了我还可以帮你看看，现在看你🐴，滚

**Comment by hnyer** [comment]
@langxing   
问这种问题的人也是醉了..
别人又没有义务给你提供什么，对你有用你就看，没有用就不要看。

**Comment by ChenTianSaber** [comment]
> @langxing
> 问这种问题的人也是醉了..
> 别人又没有义务给你提供什么，对你有用你就看，没有用就不要看。

兄弟说得好！

**Comment by hnyer** [comment]
SystemClock.sleep(1000);
Image image = imageReader.acquireNextImage();  //
这里有个坑，就是你在获取Image的时候，得先暂停1秒左右，不然就会获取失败(原因未知)。

大佬现在知道这个原因了没，我上午也是踩到这个坑了，一直返回 null 。看了你的博客才知道不是我个人的原因。

**Comment by ChenTianSaber** [comment]
> SystemClock.sleep(1000);
> Image image = imageReader.acquireNextImage(); //
> 这里有个坑，就是你在获取Image的时候，得先暂停1秒左右，不然就会获取失败(原因未知)。
> 
> 大佬现在知道这个原因了没，我上午也是踩到这个坑了，一直返回 null 。看了你的博客才知道不是我个人的原因。

很抱歉这已经是很久之前写的了...
我刚去官网看了看，acquireNextImage() 这个方法其实就是不停的从 ImageReader's queue 里取image，获取不到的原因可能就是 acquireNextImage 取的速度超过了 把image放入  ImageReader's queue 的速度，官网上对这个方法有说明：
他建议你改用 acquireLatestImage 这个方法，因为 acquireLatestImage 并且说它可以 allow slower-running processing routines to catch up to the newest frame.
那也就是说原本的 acquireNextImage 可能会出现丢帧的情况

![image](https://user-images.githubusercontent.com/16030568/97141342-82fd3700-1799-11eb-9d49-52c6b42f6f84.png)

所以首先你可以改用 acquireLatestImage 试试，其次可以把获取image的任务放在后台执行试试

希望可以帮你...这个是我大学的时候写的，从那以后我已经很久没有写过这方面的代码了...很抱歉

**Comment by hnyer** [comment]
好的，谢谢。  大佬厉害。

**Comment by ChenTianSaber** [comment]
> 好的，谢谢。 大佬厉害。

不是大佬...还在努力
